
# Get All Players
POST https://fantasy-golf-graphql-develop.up.railway.app/graphql
Content-Type: application/json

{
  "query": "query GetAllPlayers {\n  players {\n    id\n    name\n    totalPoints\n    wins\n    pgaId\n  }\n}\n",
  "variables": {}
}