
# Get All Players
POST https://fantasy-golf-graphql-develop.up.railway.app/graphql
Content-Type: application/json

{
  "query": "query GET_Players {
  getAllPlayers {
    id
    name
    pgaId
    salary
  }
}",
  "variables": {}
}