
# Get All Players
POST https://fantasy-golf-graphql-develop.up.railway.app/graphql
Content-Type: application/json

{
  "query": "query GetAllPlayers {\n  getAllPlayers {\n    id\n    name\n    pgaId\n    salary\n    avatarUrl\n  }\n}\n"
}